# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'ShareNote' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ShareNote
  pod 'SwiftLint'
  
  # Kakao
  pod 'RxKakaoSDKCommon'  # 필수 요소를 담은 공통 모듈
  pod 'RxKakaoSDKAuth'  # 카카오 로그인
  pod 'RxKakaoSDKUser'  # 사용자 관리

  # Naver
  pod 'naveridlogin-sdk-ios'

  # Firebase
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'

  #Snapkit
  pod 'SnapKit', '~> 5.0.0'

  #Alamofire
  pod 'Alamofire', '~> 5.2'

  #SwiftyBeaver
  pod 'SwiftyBeaver'

  #Then
  pod 'Then'

  #TextFieldEffects
  pod 'TextFieldEffects'

  #ReactorKit
  pod 'ReactorKit'

  #PanModal
  pod 'PanModal'

  target 'ShareNoteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ShareNoteUITests' do
    # Pods for testing
  end

end
